language: elixir

elixir:
  - 1.5.0
  - 1.5.1
  - 1.5.2

otp_release:
  - 20.1

services:
  - postgresql

before_script:
  - MIX_ENV=test mix event_store.setup
  - epmd -daemon

script:
  - mix test.all

sudo: required
dist: trusty

addons:
  postgresql: "9.6"
